runtime: nodejs16
service: default

handlers:
  - url: /
    static_files: dist/homework8/index.html
    upload: dist/homework8/index.html

  - url: /
    static_dir: dist/homework8

  - url: /
    static_files: dist/homework8/business-search.js
    upload: dist/homework8/business-search.js

  - url: /
    static_files: dist/homework8/express.js
    upload: dist/homework8/express.js
